"""initial tables

Revision ID: 0584a0e35252
Revises:
Create Date: 2026-03-05 13:32:16.122612

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0584a0e35252"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table("users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("phone", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM(
                "doctor",
                "nurse",
                "reception",
                "pharmacy",
                "lab_tech",
                "hospital_admin",
                "owner",
                name="user_role",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM("active", "inactive", "suspended", name="user_status"),
            server_default=sa.text("'active'::user_status"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "job_title", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "password_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_timestamp",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("address", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("hire_dt", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column(
            "manager_id", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "password", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["manager_id"], ["users.id"], name=op.f("users_manager_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
        sa.UniqueConstraint("phone", name=op.f("uq_users_phone")),
    )
    # ### end Alembic commands ###
