"""Add patient_id to patients

Revision ID: 3040318342be
Revises: 0001_add_all_tables
Create Date: 2026-04-14 00:20:35.164134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3040318342be'
down_revision: Union[str, Sequence[str], None] = '0001_add_all_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.alter_column('chart_entries', 'patient_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('chart_entries', 'user_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_index(op.f('ix_chart_entries_id'), 'chart_entries', ['id'], unique=False)
    op.alter_column('invoices', 'patient_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.add_column('patients', sa.Column('patient_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_patient_id'), 'patients', ['patient_id'], unique=True)
    op.alter_column('prescriptions', 'patient_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('prescriptions', 'prescribed_by_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_index(op.f('ix_prescriptions_id'), 'prescriptions', ['id'], unique=False)
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'suspended', name='user_status'),
               nullable=False,
               existing_server_default=sa.text("'active'::user_status"))
    op.alter_column('users', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'address',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'suspended', name='user_status'),
               nullable=True,
               existing_server_default=sa.text("'active'::user_status"))
    op.drop_index(op.f('ix_prescriptions_id'), table_name='prescriptions')
    op.alter_column('prescriptions', 'prescribed_by_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('prescriptions', 'patient_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_patients_patient_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_column('patients', 'patient_id')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.alter_column('invoices', 'patient_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_chart_entries_id'), table_name='chart_entries')
    op.alter_column('chart_entries', 'user_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('chart_entries', 'patient_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    # ### end Alembic commands ###
