"""Drop duration columns

Revision ID: 62d6c3d2b96b
Revises: 7c86b9aac9bf
Create Date: 2026-04-15 17:19:32.515619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d6c3d2b96b'
down_revision: Union[str, Sequence[str], None] = '7c86b9aac9bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescriptions', 'duration_val')
    op.drop_column('prescriptions', 'duration_unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescriptions', sa.Column('duration_unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('prescriptions', sa.Column('duration_val', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
