"""add_status_to_invoice

Revision ID: b4807e1e6946
Revises: 62d6c3d2b96b
Create Date: 2026-04-16 00:30:10.856514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4807e1e6946'
down_revision: Union[str, Sequence[str], None] = '62d6c3d2b96b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column as nullable first
    op.add_column('invoices', sa.Column('status', sa.String(length=20), nullable=True))
    
    # 2. Update existing rows to 'pending'
    op.execute("UPDATE invoices SET status = 'pending'")
    
    # 3. Alter column to be NOT NULL
    op.alter_column('invoices', 'status', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'status')
    # ### end Alembic commands ###
